# This is an autogenerated python class

from dataclasses_avroschema import AvroModel
import dataclasses

from dataclasses_avroschema import types
import datetime
import enum
import typing
import uuid


class PaymentStatus(str, enum.Enum):
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


@dataclasses.dataclass
class PaymentResponseAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    paymentId: uuid.UUID
    customerId: uuid.UUID
    orderId: uuid.UUID
    price: types.condecimal(max_digits=10, decimal_places=2)
    createdAt: datetime.datetime
    paymentStatus: PaymentStatus
    failureMessages: typing.List[str]

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"
