# This is an autogenerated python class

from dataclasses_avroschema import AvroModel
import dataclasses

from dataclasses_avroschema import types
import datetime
from decimal import Decimal
import enum
import typing
import uuid


class PaymentStatus(str, enum.Enum):
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


@dataclasses.dataclass
class PaymentResponseAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    paymentId: uuid.UUID
    customerId: uuid.UUID
    orderId: uuid.UUID
    createdAt: datetime.datetime
    paymentStatus: PaymentStatus
    failureMessages: typing.List[str]
    price: types.condecimal(max_digits=10, decimal_places=2)

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"

class PaymentOrderStatus(str, enum.Enum):
    PENDING = "PENDING"
    CANCELLED = "CANCELLED"


@dataclasses.dataclass
class PaymentRequestAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    customerId: uuid.UUID
    orderId: uuid.UUID
    createdAt: datetime.datetime
    paymentOrderStatus: PaymentOrderStatus
    price: types.condecimal(max_digits=10, decimal_places=2)

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"

if __name__ == '__main__':
    print(PaymentRequestAvroModel.avro_schema())

