# This is an autogenerated python class

from dataclasses_avroschema import AvroModel
import dataclasses

from dataclasses_avroschema import types
import datetime
import enum
import typing
import uuid


class PaymentStatus(str, enum.Enum):
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


@dataclasses.dataclass
class PaymentResponseAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    paymentId: uuid.UUID
    customerId: uuid.UUID
    orderId: uuid.UUID
    price: types.condecimal(max_digits=10, decimal_places=2)
    createdAt: datetime.datetime
    paymentStatus: PaymentStatus
    failureMessages: typing.List[str]

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"

class PaymentOrderStatus(str, enum.Enum):
    PENDING = "PENDING"
    CANCELLED = "CANCELLED"


@dataclasses.dataclass
class PaymentRequestAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    customerId: uuid.UUID
    orderId: uuid.UUID
    price: types.condecimal(max_digits=10, decimal_places=2)
    createdAt: datetime.datetime
    paymentOrderStatus: PaymentOrderStatus

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"

class RestaurantOrderStatus(str, enum.Enum):
    PAID = "PAID"


@dataclasses.dataclass
class Product(AvroModel):
    id: uuid.UUID
    quantity: types.Int32


@dataclasses.dataclass
class RestaurantApprovalRequestAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    restaurantId: uuid.UUID
    orderId: uuid.UUID
    restaurantOrderStatus: RestaurantOrderStatus
    products: typing.List[Product]
    price: types.condecimal(max_digits=10, decimal_places=2)
    createdAt: datetime.datetime

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"

class OrderApprovalStatus(str, enum.Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


@dataclasses.dataclass
class RestaurantApprovalResponseAvroModel(AvroModel):
    id: uuid.UUID
    sagaId: uuid.UUID
    restaurantId: uuid.UUID
    orderId: uuid.UUID
    createdAt: datetime.datetime
    orderApprovalStatus: OrderApprovalStatus
    failureMessages: typing.List[str]

    
    class Meta:
        namespace = "com.food.ordering.system.kafka.order.avro.model"
